---
- name: Check if Node.js is installed
  command: node --version
  register: nodejs_check
  ignore_errors: yes
  changed_when: false

- name: Try to install Node.js via EPEL (skip on error)
  block:
    - name: Install EPEL repository
      package:
        name: epel-release
        state: present

    - name: Install Node.js
      package:
        name: nodejs
        state: present
  when: nodejs_check.rc != 0
  ignore_errors: yes

- name: Create application directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
  loop:
    - "{{ node_app_dir }}/versions"
    - "{{ node_app_dir }}/shared"

- name: Copy Node.js app files
  copy:
    src: "../../../../apps/node-app/"
    dest: "{{ node_app_dir }}/versions/node-app-{{ node_app_version }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: Start Node.js application directly with node (fallback)
  command: node "{{ node_app_dir }}/versions/node-app-{{ node_app_version }}/index.js"
  args:
    chdir: "{{ node_app_dir }}/versions/node-app-{{ node_app_version }}"
  ignore_errors: yes
  when: nodejs_check.rc == 0
...