---
---
- name: Ensure parent directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
  loop:
    - "{{ apps_base_dir }}"
    - "{{ apps_base_dir }}/artifacts"

- name: Create application directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
  loop:
    - "{{ flask_app_dir }}/versions"
    - "{{ flask_app_dir }}/shared"
    - "{{ apps_base_dir }}/artifacts/flask-app"

- name: Copy Flask app files
  copy:
    src: "../../../../apps/flask-app/"
    dest: "{{ flask_app_dir }}/versions/flask-app-{{ flask_app_version }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0644'

- name: Create virtual environment using python3 -m venv
  command: python3 -m venv "{{ flask_app_dir }}/versions/flask-app-{{ flask_app_version }}/venv"
  args:
    creates: "{{ flask_app_dir }}/versions/flask-app-{{ flask_app_version }}/venv/bin/python"

- name: Install Python dependencies using pip from virtualenv
  pip:
    requirements: "{{ flask_app_dir }}/versions/flask-app-{{ flask_app_version }}/requirements.txt"
    virtualenv: "{{ flask_app_dir }}/versions/flask-app-{{ flask_app_version }}/venv"
    virtualenv_command: python3 -m venv

- name: Create symbolic link for current version
  file:
    src: "{{ flask_app_dir }}/versions/flask-app-{{ flask_app_version }}"
    dest: "{{ flask_app_dir }}/current"
    state: link
    force: yes

- name: Create Flask systemd service
  template:
    src: flask-app.service.j2
    dest: /etc/systemd/system/flask-app.service
    mode: '0644'

- name: Start and enable Flask service
  systemd:
    name: flask-app
    state: started
    enabled: yes
    daemon_reload: yes
...